apiVersion: v1
kind: Template
metadata:
  name: thoth-ops-infra-buildconfig
  annotations:
    description: >
      These are the BuildConfigs used to build the container images for thoth-ops to run Pod based Jobs.
    openshift.io/display-name: "Thoth thoth-ops Infrastructure"
    tags: thoth,thoth-ops,aicoe-ci,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      These are the BuildConfigs used to build the container images for thoth-ops to run Pod based Jobs.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: thoth-ops-infra-buildconfig
    app: thoth-ops
    component: infrastructure

parameters:
  - description: Git repository for thoth-ops-infra
    displayName: Thoth's thoth-ops Infrastructure git repository
    required: true
    name: GITHUB_URL
    value: "https://github.com/thoth-station/thoth-ops-infra"

  - description: Git reference to be used within thoth-ops-infra
    displayName: Thoth's thoth-ops Infrastructure git reference
    required: true
    name: GITHUB_REF
    value: "master"

objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      labels:
        app: "thoth-ops"
        component: "infrastructure"
      name: "thoth-coala-ubi8"
    spec:
      resources:
        requests:
          memory: "1Gi"
          cpu: "1"
        limits:
          memory: "1Gi"
          cpu: "1"
      output:
        to:
          kind: ImageStreamTag
          name: "thoth-coala:ubi8"
      source:
        type: Git
        git:
          uri: "${GITHUB_URL}"
          ref: ${GITHUB_REF}
        contextDir: "thoth-coala-ubi8"
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      triggers:
        - type: ImageChange
          imageChange: {}

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      labels:
        app: "thoth-ops"
        component: "infrastructure"
      name: "thoth-pylint-ubi8"
    spec:
      resources:
        requests:
          memory: "1Gi"
          cpu: "1"
        limits:
          memory: "1Gi"
          cpu: "1"
      output:
        to:
          kind: ImageStreamTag
          name: "thoth-pylint:ubi8"
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: "${GITHUB_URL}"
          ref: ${GITHUB_REF}
        contextDir: "thoth-pylint-ubi8"
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      triggers:
        - type: ImageChange
          imageChange: {}

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      labels:
        app: "thoth-ops"
        component: "infrastructure"
      name: "thoth-pytest-ubi8"
    spec:
      resources:
        requests:
          memory: "1Gi"
          cpu: "1"
        limits:
          memory: "1Gi"
          cpu: "1"
      output:
        to:
          kind: ImageStreamTag
          name: "thoth-pytest:ubi8"
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: "${GITHUB_URL}"
          ref: ${GITHUB_REF}
        contextDir: "thoth-pytest-ubi8"
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      triggers:
        - type: ImageChange
          imageChange: {}

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      labels:
        app: "thoth-ops"
        component: "infrastructure"
      name: "thoth-ops"
    spec:
      resources:
        requests:
          memory: "1Gi"
          cpu: "1"
        limits:
          memory: "1Gi"
          cpu: "1"
      output:
        to:
          kind: ImageStreamTag
          name: "thoth-ops:v0.17.0"
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: "${GITHUB_URL}"
          ref: ${GITHUB_REF}
        contextDir: "thoth-openshift-client"
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      triggers:
        - type: ImageChange
          imageChange: {}
