apiVersion: v1
kind: Template
metadata:
  name: thoth-ops-infra-imagestream
  annotations:
    description: >
      These are the ImageStream used by thoth-ops to run Pod based Jobs.
    openshift.io/display-name: "Thoth thoth-ops Infrastructure"
    tags: thoth,thoth-ops,aicoe-ci,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      These are the ImageStream used by thoth-ops to run Pod based Jobs.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: thoth-ops-infra-imagestream
    app: thoth-ops
    component: infrastructure

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: "thoth-ops"
        component: "infrastructure"
      name: "thoth-python36"
    spec:
      lookupPolicy:
        local: true
    tags:
      - name: "fedora28"
        referencePolicy:
          type: Source
      - name: "ubi8"
        referencePolicy:
          type: Source

  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: "thoth-ops"
        component: "infrastructure"
      name: "s2i-thoth-ubi8-py36"
    spec:
      lookupPolicy:
        local: true
    tags:
      - name: "v0.15.0"
        referencePolicy:
          type: Source

  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: thoth-ops
        component: infrastructure
      name: "thoth-pylint"
    spec:
      lookupPolicy:
        local: true
    tags:
      - name: "fedora28"
        referencePolicy:
          type: Source
      - name: "ubi8"
        referencePolicy:
          type: Source

  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: thoth-ops
        component: infrastructure
      name: "thoth-coala"
    spec:
      lookupPolicy:
        local: true
    tags:
      - name: "fedora28"
        referencePolicy:
          type: Source
      - name: "ubi8"
        referencePolicy:
          type: Source

  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: thoth-ops
        component: infrastructure
      name: "thoth-pytest"
    spec:
      lookupPolicy:
        local: true
    tags:
      - name: "fedora28"
        referencePolicy:
          type: Source
      - name: "ubi8"
        referencePolicy:
          type: Source

  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: "thoth-ops"
        component: "infrastructure"
      name: "thoth-ops"
    spec:
      lookupPolicy:
        local: true
    tags:
      - name: "v0.17.0"
        referencePolicy:
          type: Source
